Componente input
AlexHRodrii/ABP-Frontend pull request #1
Opened 2023-03-14 19:22 UTC by Danielluengo15

2023-03-14 19:37 UTC, AlexHRodrii requested changes
Revisar y añadir lo especificado

2023-03-14 19:37 UTC, AlexHRodrii commented on src/app/components/input/input.component.html
> +<div class="input-container">
Para que se utiliza la clase input container?

2023-03-14 19:37 UTC, AlexHRodrii commented on src/app/app.module.ts
Añadir una captura en la descripción de la PR con el resultado del componente para ver como queda

2023-03-14 19:37 UTC, AlexHRodrii commented on src/app/components/input/input.component.ts
> +export class InputComponent {
Si es posible las props en inglés mejor

2023-03-14 19:37 UTC, AlexHRodrii commented on src/app/components/input/input.component.html
> +<div class="input-container">
Añadir lógica para que si no se cumple la validación se cambie el borde de color

2023-03-15 15:23 UTC, Danielluengo15 commented
![imagen](https://user-images.githubusercontent.com/122672231/225357381-741727fe-b4ce-47b4-9bc0-57dc5800ebc1.png)

2023-03-15 18:18 UTC, AlexHRodrii approved these changes

2023-03-15 18:18 UTC, merged