Componente texto
AlexHRodrii/ABP-Frontend pull request #2
Opened 2023-03-14 19:23 UTC by Danielluengo15

2023-03-14 19:41 UTC, AlexHRodrii requested changes
Añadir lo que falta y la captura del componente en funcionamiento

2023-03-14 19:41 UTC, AlexHRodrii commented on src/app/components/texto/texto.component.ts
> +export class TextoComponent {
Añadir propiedad para el color del texto y si lo queremos en negrita

2023-03-14 19:41 UTC, AlexHRodrii commented on src/app/components/texto/texto.component.html
> +<p [style.font-size.px]="sizeTexto" [style.font-family]="fuenteTexto">{{ texto }}</p>
Cambiar unidad de medida del texto (en vez de píxeles usar rem)

2023-03-15 13:51 UTC, Danielluengo15 commented
![imagen](https://user-images.githubusercontent.com/122672231/225329158-743181e1-8043-4382-a0a8-511d44f59b43.png)

2023-03-15 18:19 UTC, AlexHRodrii approved these changes

2023-03-15 18:24 UTC, AlexHRodrii approved these changes

2023-03-15 18:24 UTC, merged