Componente boton
AlexHRodrii/ABP-Frontend pull request #3
Opened 2023-03-14 19:24 UTC by Danielluengo15

2023-03-14 19:43 UTC, AlexHRodrii requested changes
Lo comentado y añadir captura del componente en funcionamiento

2023-03-14 19:43 UTC, AlexHRodrii commented on src/app/components/boton/boton.component.html
> +<button [style.font-size]="fontSize" [style.color]="colorLetra" [style.background-color]="colorFondo" [style.border]="borde" (click)="onClick.emit()">
Falta lógica para la altura, el tamaño, la fuente y añadir algún efecto de click con css o js

2023-03-15 11:29 UTC, Danielluengo15 commented
![imagen](https://user-images.githubusercontent.com/122672231/225296158-ae67aa65-5fdc-41d8-9d67-9d36bb93fe8b.png)

2023-03-15 18:25 UTC, AlexHRodrii approved these changes

2023-03-15 18:26 UTC, AlexHRodrii approved these changes

2023-03-15 18:26 UTC, merged